name: Linux - Full Access

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Linux Access...
    runs-on: ubuntu-latest
    timeout-minutes: 9999
    
    steps:
      - name: Update & Install Dependencies
        run: |
          sudo apt update && sudo apt upgrade -y
          sudo apt install -y curl wget git nano tmux
          
      - name: Download & Install RustDesk (Remote Access)
        run: |
          wget https://github.com/rustdesk/rustdesk/releases/latest/download/rustdesk-1.2.0-x86_64.deb
          sudo dpkg -i rustdesk-1.2.0-x86_64.deb || sudo apt-get install -f -y
          nohup rustdesk &

      - name: Display RustDesk Info
        run: rustdesk --help || echo "RustDesk installed. Open the client and enter the machine ID to connect."

      - name: Setup Time Counter
        run: |
          echo "while true; do date; sleep 60; done" > time.sh
          chmod +x time.sh
          nohup bash time.sh &

      - name: Keep Machine Alive
        run: tmux new-session -d 'bash'
